### ISSUE TITLE
Remove highlighting of number line

### ISSUE THREAD

**Issue by slandau4** [nightsense/office#2]
Hello, I'm using vim on iterm 2 with the office-dark theme. Is there a way to remove the highlighting from the number line so that it will look like it does on vimcolors?

My screen: 
<img width="1276" alt="screen shot 2017-10-17 at 11 32 02 am" src="https://user-images.githubusercontent.com/29212446/31674069-d2bfc262-b32e-11e7-9f77-c722e05663c3.png">

vim color: http://vimcolors.com/721/office-dark/dark

**Comment by nightsense** [comment]
Hi @slandau4, I like the idea so I just added that as an option. Update the theme and put `let g:office_dark_CursorLineNr = 'off'` in your vimrc, and you should be good to go.

**Comment by slandau4** [comment]
Hey, I just updated (:PlugUpdate) and added that option but it doesn't seem to have changed the number line. 
<img width="1277" alt="screen shot 2017-10-17 at 2 18 04 pm" src="https://user-images.githubusercontent.com/29212446/31681752-22ce3614-b346-11e7-8de4-2789720d18cc.png">

**Comment by nightsense** [comment]
Oh whoops, now I get what you mean! OK, new option added: `let g:office_dark_LineNr = 'off'
`

**Comment by slandau4** [comment]
Perfect! 
<img width="1276" alt="screen shot 2017-10-17 at 2 51 32 pm" src="https://user-images.githubusercontent.com/29212446/31683334-b4d09bc0-b34a-11e7-8e58-61d368ca9bf5.png">

Thank you so much for taking care of this so quickly!

**Comment by nightsense** [comment]
No prob, enjoy! :frog:
